/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-04-21 08:27:24 
*/
export interface IMobiAPIClient {
    headers: { 'Content-Type': string; };
    host: string;
}
