/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-04-23 09:23:30 
 * Interface is a structure that defines the contract in your application.
 * https://www.tutorialsteacher.com/typescript/typescript-interface
*/
export interface IProductAPIClient {
    get(): Promise<Response>;
    post(): void;
}
