/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-04-19 03:07:44 
*/
import MobiAPIClient from "./APIClient";

export interface IStoreAPIClient {
    getById(id: string): {};
    get(): {};
    post(data: any): {};
}
